# ==============================
# GROUPE MONITORING
# ==============================
# Ce serveur va héberger les outils de supervision :
# - Prometheus (collecte des métriques)
# - Grafana (visualisation des dashboards)
[monitoring]
monitoring-server ansible_host=35.180.131.136


# ==============================
# GROUPE WEB
# ==============================
# Serveur applicatif (web / API / service)
# On y installera Node Exporter pour remonter :
# CPU, RAM, disque, réseau
[web]
web-server ansible_host=13.38.123.112


# ==============================
# GROUPE DATABASE
# ==============================
# Serveur base de données
# Même principe : Node Exporter pour les métriques système
[db]
db-server ansible_host=15.236.206.107


# ==============================
# VARIABLES GLOBALES ANSIBLE
# ==============================
[all:vars]

# Utilisateur utilisé pour se connecter en SSH sur les machines AWS
ansible_user=ubuntu

# Clé SSH générée par Terraform pour accéder aux instances
ansible_ssh_private_key_file=~/GRAF_PROMETHEUS_AWS/terraform/aws_monitoring_auto/monitoring-key.pem